# Generated by Django 4.0.1 on 2023-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='URL',
            field=models.URLField(blank=True, default=''),
        ),
    ]
