# Generated by Django 4.0.1 on 2023-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0002_alter_reward_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='URL',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='datetime_expiration',
            field=models.DateField(blank=True, default='1900-11-11', max_length=50),
        ),
    ]
