# Generated by Django 4.0.1 on 2023-10-20 16:47

import datetime
from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0003_alter_reward_url_alter_reward_datetime_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='URL',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='create_datetime',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 20), max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='update_datetime',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 20), max_length=50),
        ),
    ]
