# Generated by Django 4.0.1 on 2023-11-13 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0006_alter_reward_create_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='URL',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='create_datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 13, 14, 34, 50, 331151), max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='update_datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 13, 14, 34, 50, 331151), max_length=50),
        ),
    ]
