# Generated by Django 4.1.7 on 2023-06-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_alter_user_born_date'),
        ('DataInit', '0006_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=3)),
                ('NIT', models.CharField(max_length=15)),
                ('timetable', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.category')),
                ('country_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataInit.country')),
                ('department_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataInit.department')),
                ('user_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
