# Generated by Django 4.1.5 on 2023-01-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_documento', models.CharField(default='', max_length=70)),
                ('Des_documento', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
