# Generated by Django 4.1.7 on 2023-04-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=150)),
                ('name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('document_type', models.CharField(default='', max_length=4)),
                ('document_number', models.CharField(default='', max_length=15)),
                ('telephone', models.CharField(default='', max_length=12)),
                ('email', models.EmailField(default='', max_length=254)),
                ('born_date', models.DateField(blank=True)),
                ('department', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=100)),
                ('photo', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
