# Generated by Django 4.0.1 on 2023-08-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='object_company',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
