# Generated by Django 4.1.7 on 2023-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clientType',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='partnerType',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='primaryUser',
            field=models.BooleanField(default=False),
        ),
    ]
