# Generated by Django 4.1.7 on 2023-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_clienttype_user_partnertype_user_primaryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='born_date',
            field=models.DateField(default='1900-11-11'),
        ),
    ]
