# Generated by Django 4.0.1 on 2023-08-30 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_user_object_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='object_company',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, null=True, size=None),
        ),
    ]
