# Generated by Django 4.0.1 on 2023-10-30 16:03

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_user_object_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_File',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
    ]
