# Generated by Django 4.0.1 on 2023-11-03 20:35

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_user_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_File',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
    ]
