# Generated by Django 4.0.1 on 2023-11-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_user_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_File',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
