# Generated by Django 4.1.7 on 2023-04-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataInit', '0002_city_country_department_delete_estado_delete_pais_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
