# Generated by Django 4.1.7 on 2023-04-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataInit', '0003_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataInit.department')),
            ],
        ),
    ]
